# # 1. Write a program that prompts the user to input a series of numbers until they
# # input a duplicate number. Use a while loop to check for duplicates.
# numbers = []
# while True:
#     num = int(input("Enter a number: "))
#     if num in numbers:
#         print("Duplicate number entered:", num)
#         break
#     numbers.append(num)
# print("Numbers entered:", numbers)

num = int(input("Enter a positive integer: "))
count = 1
while count <= 10:
    factorial= num*count
    print(f"{num} x {count} = {factorial}")
    count += 1
    
    
# 3. Write a program that accepts a number from the user and calculates the sum of
# all numbers from 1 up to that number.
# 4. Given a list of numbers, use a loop to count how many times a specific number for
# example 10 appears.
# 5. Write a program that counts the total number of vowels and consonants in a given
# sentence, ignoring spaces and special characters.
# 6. Write a program to count the total number of digits in a given integer.
# 7. Generate a sequence until it reaches 1. If you start with any positive integer n, and
# if n is even, divide it by 2; if n is odd, multiply it by 3 and add 1. Repeat the process.
# The sequence will always eventually reach 1. Write a program to print this
# sequence for a given number.
# given input: n = 6
# expected output: 6, 3, 10, 5, 16, 8, 4, 2, 1
# 8. Print alphabet Series from A–Z
# 9. Write a program that prompts the user for a starting integer and an ending integer.
# Use a while loop to print all numbers between them, inclusive.
# 10. Write a program that prints all odd numbers between 1 and 50 in descending
# order from 49 down to 1 using a while loop.
# 11. Write a program that prints all multiples of 7 between 1 and 100.
# 12. Write a program that continuously prompts the user to input numbers. The loop
# should terminate immediately when the user enters 0. Afterward, print the total
# sum of all numbers entered excluding the 0.
# 13. Write a program that asks a user to enter their age. If the input is less than 0 or
# greater than 120, print invalid age and prompt them again. The loop should
# repeat until a valid age is provided.
# 14. Write a program that allows a teacher to input student scores one by one. The loop
# ends when the teacher types -1. The program should then calculate and display
# the average score.
# 15. Write a program that simulates a login screen. Give the user a maximum of 3
# attempts to type the correct password for example secret123. If they fail 3 times,
# print access denied, if they succeed early, print access granted and exit the loop.
# 16. Write a program that takes an integer input and constructs a new integer that is
# the exact reverse of the input for example input is 582 outputs the actual integer
# 285.
# 17. Write a program that uses a while loop to print the first n terms of the Fibonacci
# sequence 0, 1, 1, 2, 3, 5, 8 where n is provided by the user.
# 18. Write a program that loops through a string using a while loop and prints a new
# version of the string with all the vowels removed.
# 19. Write a program that scans a string using a while loop index to count how many
# times the specific two-character substring hi appears.
# 20. Write a program to find and print all numbers in the list that are multiples of 5.
# numbers = [12, 25, 7, 30, 18, 40, 55, 9]
# 21. Write a program that processes a string character by character using a while loop,
# converting all lowercase letters to uppercase and vice versa.
# 22. For every single increment of the outer loop i, how many times does the inner loop
# j run?
# 23. Why does this code print only two stars instead of six? What mistake was made
# with variable j?
# 24. Which is the first integer whose square is strictly greater than 20?
# 25. If the user inputs 4, 7, -1, and 10 in sequence, is the -1 added to the total? What is
# the final printed total?
# 26. How many times does the word loop print? What is the final value of x?
# 27. In many languages, an integer can act as a Boolean expression. At what point does
# x evaluate to False?
# 28. What famous mathematical number sequence is generated by this loop's variable
# updating logic?
# 29. Write a Python function that accepts a string and counts the number of upper and
# lower case letters.
# sample string : 'The quick Brow Fox'
# expected output :
# No. of upper case characters : 3
# No. of lower case characters : 12
# 30. Write a program that displays the following menu repeatedly until the user
# chooses to exit:
# 1. Add two numbers
# 2. Subtract two numbers
# 3. Multiply two numbers
# 4. Exit
# 31. Write a program that repeatedly asks the user to enter numbers until they enter
# 0. Count how many positive and negative numbers were entered exclude 0.
# 32. Write a program that takes two numbers start and end and prints all prime
# numbers between them using while loops.
# 33. Write a program to find the numbers which are below 20 in the list.
# numbers = [12, 40, 21, 31, 10, 7, 5]
# 34. Write a program to replace all numbers greater than 50 with 0 in the list and print
# the updated list.
# numbers = [45, 60, 12, 75, 30, 55, 8, 90]
# 35. Write a program to count how many numbers are divisible by both 3 and 5 in the
# list.
# numbers = [15, 25, 30, 45, 60, 12, 90, 7]
# 36. Write a program to check whether the list is in ascending order or not using a
# while loop. Print sorted or not sorted numbers = [10, 15, 25, 30, 45]
# 37. Print alphabet series a to z.
# 38. Write a program that iterates through the list of chapter page counts [45, 30, 50,
# 40] and starting the count at 1 to print a message for each chapter in the format:
# Chapter [Number] has [Pages] pages
# 39. You have two lists of numbers, and you need to find out which numbers appear
# in both lists.
# Given two lists of numbers [1,2,3,4,5] and [3,4,5,6,7]
# 40. Print multiplication table of 2,4,6,7,8
# 41. Write a program to check whether the list contains any duplicate numbers or not
# using a while loop. If the list has any duplicate, print has Duplicates, otherwise
# print no duplicates.